DSG-1635/Upgrade-to-Spring-Boot-3.1
Nuvalence/dsgov-portal-api pull request #42
Opened 2023-10-04 18:14 UTC by afcalderonm

## Description

Upgrade SpringBoot version

[___JIRA_TICKET_TITLE___](//jira_url)

## Motivation and Context

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
  Minor
- [ ] New feature (non-breaking change which adds functionality)
  Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-10-05 18:05 UTC, afcalderonm commented
/gcbrun

2023-10-05 20:30 UTC, asultan001 approved these changes
LGTM but I'd like for @deibys-nuvalence to give it another look just in case.

2023-10-05 20:39 UTC, deibys-nuvalence commented on service/build.gradle
> +	id 'org.springframework.boot' version '3.1.3'
At the time , I upgrade to,  3.1.3 was the latest , but now 3.1.4 is the newest one . I dont think there would be any issue upgrading to 3.1.4

2023-10-05 20:44 UTC, deibys-nuvalence commented on service/build.gradle
>  	// version bump to address known CVEs
This dependency was added to override the one pulled by dependency setup (which at the time was a lower version)
implementation 'org.yaml:snakeyaml:2.2'
With spring boot 3 upgrade, this library with this versions or higher should be brought up
I guess if you check the dependency tree and that libraries is already pulled with this version, you can remove these direct dependency inclusion

2023-10-05 20:52 UTC, deibys-nuvalence requested changes
Just move to 3.1.4
Also be aware when you deploy to dev, the artifact repository should be updated. At least I had problems when deploying to dev
 repositories {
        mavenCentral()
        maven {
            url 'https://oss.sonatype.org/content/repositories/snapshots/'
        }
    }
as this currently brings snapshot dependencies

2023-10-05 21:05 UTC, deibys-nuvalence approved these changes

2023-10-06 03:41 UTC, afcalderonm commented on service/build.gradle
> +	id 'org.springframework.boot' version '3.1.3'
Done

2023-10-06 03:43 UTC, afcalderonm commented on service/build.gradle
>  	// version bump to address known CVEs
i tried removing and check in the dependency tree and there was brought up with the springboot dependency but it still using the 1.33 version that has a vulnerability  so i think is better to keep this one

2023-10-06 12:38 UTC, deibys-nuvalence approved these changes

2023-10-06 15:03 UTC, merged